inhibit_all_warnings!

platform :ios, '7.0'

pod 'AFNetworking', '~> 2.5.4'
pod 'SDWebImage', '~> 3.7.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'iCarousel', '~> 1.8.1'
pod 'MJExtension', '~> 2.5.3'
pod 'Masonry', '~> 0.6.2'
pod 'DKNightVersion', '~> 0.8.1'
